"""fase 1: territorio e catalogo de fontes

Revision ID: 112beed5bb40
Revises: 
Create Date: 2026-09-12 23:30:33.459195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '112beed5bb40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cena_satelite',
    sa.Column('fonte', sa.Enum('SENTINEL2_L2A', name='fonte_cena'), nullable=False),
    sa.Column('tile_id', sa.String(length=60), nullable=False),
    sa.Column('data_aquisicao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cobertura_nuvem_cena_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status_processamento', sa.Enum('PENDENTE', 'PROCESSADA', 'REJEITADA', name='status_processamento_cena'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estacao_meteorologica',
    sa.Column('fonte', sa.Enum('INMET', 'NASA_POWER', 'OUTRA', name='fonte_estacao'), nullable=False),
    sa.Column('codigo_externo', sa.String(length=60), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('altitude_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('operador', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.Enum('OBSERVADO', 'GRADE', name='tipo_estacao'), nullable=False),
    sa.Column('variaveis_disponiveis', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('periodo_inicio_serie', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_fim_serie', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execucao_processamento',
    sa.Column('tipo', sa.Enum('INGESTAO_CLIMA', 'INGESTAO_SATELITE', 'INDICE_VEGETACAO', 'DIAGNOSTICO', 'CENARIO', name='tipo_execucao'), nullable=False),
    sa.Column('entrada_fontes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('versao_pipeline', sa.String(length=50), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SUCESSO', 'FALHA', 'PARCIAL', 'EM_ANDAMENTO', name='status_execucao'), nullable=False),
    sa.Column('saida_referencias', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fazenda',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('proprietario', sa.String(length=200), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_total_ha', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OBSERVADO', 'DERIVADO', 'ESTIMADO', 'DECLARADO', 'HIPOTESE', name='status_evidencia'), nullable=False),
    sa.Column('qualidade', sa.Enum('ALTA', 'MEDIA', 'BAIXA', 'INSUFICIENTE', name='qualidade_evidencia'), nullable=False),
    sa.Column('data_obtencao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('versao_processamento', sa.String(length=50), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_fim', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedor',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('ANIMAIS', 'INSUMOS', 'SERVICOS', 'FRETE', 'COMPRADOR', name='tipo_fornecedor'), nullable=False),
    sa.Column('regiao', sa.String(length=200), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_produtiva',
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tipo_uso', sa.Enum('PASTO', 'MATA', 'AGUA', 'LAVOURA', 'INFRAESTRUTURA', 'OUTRO', name='tipo_uso'), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('area_utilizavel_ha', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sistema_produtivo', sa.Enum('CORTE', 'LEITE', 'AGRICULTURA', 'MISTO', 'NAO_DEFINIDO', name='sistema_produtivo'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OBSERVADO', 'DERIVADO', 'ESTIMADO', 'DECLARADO', 'HIPOTESE', name='status_evidencia'), nullable=False),
    sa.Column('qualidade', sa.Enum('ALTA', 'MEDIA', 'BAIXA', 'INSUFICIENTE', name='qualidade_evidencia'), nullable=False),
    sa.Column('data_obtencao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('versao_processamento', sa.String(length=50), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_fim', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao_representatividade',
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('estacao_id', sa.UUID(), nullable=False),
    sa.Column('variavel', sa.Enum('PRECIPITACAO', 'TEMPERATURA', 'UMIDADE_RELATIVA', 'RADIACAO', 'VENTO', name='variavel_meteorologica'), nullable=False),
    sa.Column('distancia_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('criterio_completude', sa.String(length=30), nullable=True),
    sa.Column('criterio_atualizacao', sa.String(length=30), nullable=True),
    sa.Column('criterio_consistencia', sa.String(length=30), nullable=True),
    sa.Column('papel', sa.Enum('REFERENCIA', 'AUXILIAR', name='papel_representatividade'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['estacao_id'], ['estacao_meteorologica.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe',
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_pessoas', sa.Integer(), nullable=False),
    sa.Column('funcoes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('disponibilidade_sazonal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competencias', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('apoio_tecnico', sa.Enum('PROPRIO', 'CONTRATADO', 'NENHUM', name='apoio_tecnico'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observacao_meteorologica',
    sa.Column('estacao_id', sa.UUID(), nullable=False),
    sa.Column('variavel', sa.Enum('PRECIPITACAO', 'TEMPERATURA', 'UMIDADE_RELATIVA', 'RADIACAO', 'VENTO', name='variavel_meteorologica'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=30), nullable=False),
    sa.Column('flag_qualidade', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['estacao_id'], ['estacao_meteorologica.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta_regional',
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=False),
    sa.Column('especificacao', sa.String(length=500), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=False),
    sa.Column('quantidade_disponivel', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('quantidade_minima', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('condicoes', sa.String(length=500), nullable=True),
    sa.Column('sazonalidade', sa.String(length=200), nullable=True),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validade_cotacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_produtor',
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('objetivos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('capital_disponivel', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('limite_investimento', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('capital_giro', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tolerancia_risco', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='tolerancia_risco'), nullable=False),
    sa.Column('disponibilidade_gestao_horas_semana', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto_infraestrutura',
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('AGUA', 'CURRAL', 'CERCA', 'GALPAO', 'ACESSO', 'OUTRO', name='tipo_infraestrutura'), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_uso_area',
    sa.Column('area_produtiva_id', sa.UUID(), nullable=False),
    sa.Column('uso', sa.Enum('PASTO', 'MATA', 'AGUA', 'LAVOURA', 'INFRAESTRUTURA', 'OUTRO', name='tipo_uso'), nullable=False),
    sa.Column('vigencia_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vigencia_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declarado_por', sa.String(length=200), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_produtiva_id'], ['area_produtiva.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indice_vegetacao_area',
    sa.Column('area_produtiva_id', sa.UUID(), nullable=False),
    sa.Column('cena_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('NDVI', 'EVI', name='tipo_indice_vegetacao'), nullable=False),
    sa.Column('data_aquisicao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cobertura_valida_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mediana', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('p10', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('p25', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('p75', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('p90', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('desvio_padrao', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('versao_processamento', sa.String(length=50), nullable=False),
    sa.Column('raster_ref', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_produtiva_id'], ['area_produtiva.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cena_id'], ['cena_satelite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistica_oferta',
    sa.Column('oferta_id', sa.UUID(), nullable=False),
    sa.Column('distancia_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('custo_frete', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['oferta_regional.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # nota: 'spatial_ref_sys' e uma tabela de sistema do PostGIS (criada pela
    # extensao), nao faz parte do nosso schema — nunca deve ser criada/apagada
    # por esta migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logistica_oferta')
    op.drop_table('indice_vegetacao_area')
    op.drop_table('historico_uso_area')
    op.drop_table('ponto_infraestrutura')
    op.drop_table('perfil_produtor')
    op.drop_table('oferta_regional')
    op.drop_table('observacao_meteorologica')
    op.drop_table('equipe')
    op.drop_table('avaliacao_representatividade')
    op.drop_table('area_produtiva')
    op.drop_table('fornecedor')
    op.drop_table('fazenda')
    op.drop_table('execucao_processamento')
    op.drop_table('estacao_meteorologica')
    op.drop_table('cena_satelite')
    # ### end Alembic commands ###

    # op.drop_table() nao remove os tipos ENUM nomeados do Postgres associados
    # as colunas (alembic nao rastreia as colunas de uma tabela ja dropada) —
    # sem isso, um downgrade seguido de upgrade falha com "type already exists".
    for enum_name in (
        "status_evidencia",
        "qualidade_evidencia",
        "tipo_uso",
        "sistema_produtivo",
        "tipo_infraestrutura",
        "fonte_estacao",
        "tipo_estacao",
        "variavel_meteorologica",
        "papel_representatividade",
        "fonte_cena",
        "status_processamento_cena",
        "tipo_indice_vegetacao",
        "tolerancia_risco",
        "apoio_tecnico",
        "tipo_fornecedor",
        "tipo_execucao",
        "status_execucao",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
