"""fase 2: status em observacao, criterios como enum, constraints de unicidade

Revision ID: 65994b4484fe
Revises: 112beed5bb40
Create Date: 2026-09-13 00:12:21.689183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65994b4484fe'
down_revision: Union[str, None] = '112beed5bb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    nivel_criterio = sa.Enum(
        "BOM", "REGULAR", "INSUFICIENTE", name="nivel_criterio_representatividade"
    )
    nivel_criterio.create(op.get_bind(), checkfirst=True)

    op.add_column('avaliacao_representatividade', sa.Column('calculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('avaliacao_representatividade', sa.Column('versao_algoritmo', sa.String(length=50), nullable=True))
    op.alter_column('avaliacao_representatividade', 'criterio_completude',
               existing_type=sa.VARCHAR(length=30),
               type_=nivel_criterio,
               postgresql_using='criterio_completude::nivel_criterio_representatividade',
               nullable=False)
    op.alter_column('avaliacao_representatividade', 'criterio_atualizacao',
               existing_type=sa.VARCHAR(length=30),
               type_=nivel_criterio,
               postgresql_using='criterio_atualizacao::nivel_criterio_representatividade',
               nullable=False)
    op.alter_column('avaliacao_representatividade', 'criterio_consistencia',
               existing_type=sa.VARCHAR(length=30),
               type_=nivel_criterio,
               postgresql_using='criterio_consistencia::nivel_criterio_representatividade',
               nullable=False)
    op.create_unique_constraint('uq_avaliacao_fazenda_estacao_variavel', 'avaliacao_representatividade', ['fazenda_id', 'estacao_id', 'variavel'])
    op.add_column('observacao_meteorologica', sa.Column('status', sa.Enum('OBSERVADO', 'DERIVADO', 'ESTIMADO', 'DECLARADO', 'HIPOTESE', name='status_evidencia', create_type=False), server_default='OBSERVADO', nullable=False))
    op.add_column('observacao_meteorologica', sa.Column('versao_processamento', sa.String(length=50), nullable=True))
    op.create_unique_constraint('uq_observacao_estacao_variavel_timestamp', 'observacao_meteorologica', ['estacao_id', 'variavel', 'timestamp'])

    # Novo valor no enum tipo_execucao (Fase 2 passa a rastrear avaliacoes de
    # representatividade como execucao). ALTER TYPE ... ADD VALUE nao pode
    # rodar na mesma transacao que referencia o valor novo, daí o bloco
    # autocommit isolado aqui (nenhuma linha desta migration usa o valor).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE tipo_execucao ADD VALUE IF NOT EXISTS 'AVALIACAO_REPRESENTATIVIDADE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_observacao_estacao_variavel_timestamp', 'observacao_meteorologica', type_='unique')
    op.drop_column('observacao_meteorologica', 'versao_processamento')
    op.drop_column('observacao_meteorologica', 'status')
    op.drop_constraint('uq_avaliacao_fazenda_estacao_variavel', 'avaliacao_representatividade', type_='unique')
    op.alter_column('avaliacao_representatividade', 'criterio_consistencia',
               existing_type=sa.Enum('BOM', 'REGULAR', 'INSUFICIENTE', name='nivel_criterio_representatividade'),
               type_=sa.VARCHAR(length=30),
               postgresql_using='criterio_consistencia::text',
               nullable=True)
    op.alter_column('avaliacao_representatividade', 'criterio_atualizacao',
               existing_type=sa.Enum('BOM', 'REGULAR', 'INSUFICIENTE', name='nivel_criterio_representatividade'),
               type_=sa.VARCHAR(length=30),
               postgresql_using='criterio_atualizacao::text',
               nullable=True)
    op.alter_column('avaliacao_representatividade', 'criterio_completude',
               existing_type=sa.Enum('BOM', 'REGULAR', 'INSUFICIENTE', name='nivel_criterio_representatividade'),
               type_=sa.VARCHAR(length=30),
               postgresql_using='criterio_completude::text',
               nullable=True)
    op.drop_column('avaliacao_representatividade', 'versao_algoritmo')
    op.drop_column('avaliacao_representatividade', 'calculado_em')
    # ### end Alembic commands ###

    sa.Enum(name="nivel_criterio_representatividade").drop(op.get_bind(), checkfirst=True)

    # Reverte o novo valor de tipo_execucao recriando o tipo sem ele — Postgres
    # nao suporta DROP VALUE em enum. Seguro aqui porque, em qualquer ambiente
    # de dev fazendo downgrade logo apos o upgrade, execucao_processamento
    # nao tera linhas usando 'avaliacao_representatividade'.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE tipo_execucao RENAME TO tipo_execucao_old")
        op.execute(
            "CREATE TYPE tipo_execucao AS ENUM "
            "('INGESTAO_CLIMA', 'INGESTAO_SATELITE', 'INDICE_VEGETACAO', 'DIAGNOSTICO', 'CENARIO')"
        )
        op.execute(
            "ALTER TABLE execucao_processamento "
            "ALTER COLUMN tipo TYPE tipo_execucao USING tipo::text::tipo_execucao"
        )
        op.execute("DROP TYPE tipo_execucao_old")
