"""fase 4 tendencia vegetacao area

Revision ID: 92a9f082851f
Revises: f6de4a12b01d
Create Date: 2026-09-14 01:35:40.790732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a9f082851f'
down_revision: Union[str, None] = 'f6de4a12b01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tendencia_vegetacao_area',
    sa.Column('area_produtiva_id', sa.UUID(), nullable=False),
    sa.Column('janela_dias', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periodo_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valor_medio_periodo', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('inclinacao_diaria', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('variacao_pct_periodo', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('classificacao', sa.Enum('QUEDA', 'ESTAVEL', 'ALTA', 'DADOS_INSUFICIENTES', name='classificacao_tendencia'), nullable=False),
    sa.Column('amostras_periodo', sa.Integer(), nullable=False),
    sa.Column('comparacao_sazonal_disponivel', sa.Boolean(), nullable=False),
    sa.Column('valor_medio_periodo_anterior', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('variacao_sazonal_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('amostras_periodo_anterior', sa.Integer(), nullable=True),
    sa.Column('calculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('versao_algoritmo', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_produtiva_id'], ['area_produtiva.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###

    # `tipo` reusa o enum `tipo_indice_vegetacao` ja criado pela Fase 3 —
    # adicionado via op.add_column (ALTER TABLE), nao inline no create_table,
    # porque o visitor de DDL do create_table tenta recriar qualquer enum
    # referenciado inline sem checar se ja existe (falha com "type already
    # exists"); ALTER TABLE ADD COLUMN nao tenta criar o tipo, so referencia
    # pelo nome — mesmo motivo pelo qual enums novos (nunca criados antes)
    # precisam de `.create(checkfirst=True)` explicito antes de um
    # add_column, mas aqui o tipo ja existe, entao so referenciar basta.
    op.add_column(
        'tendencia_vegetacao_area',
        sa.Column('tipo', sa.Enum('NDVI', 'EVI', name='tipo_indice_vegetacao', create_type=False), nullable=False),
    )
    op.create_unique_constraint(
        'uq_tendencia_vegetacao_area_tipo', 'tendencia_vegetacao_area', ['area_produtiva_id', 'tipo']
    )

    # Novo valor no enum tipo_execucao (Fase 4 passa a rastrear tendencia de
    # vegetacao como execucao). ALTER TYPE ... ADD VALUE nao pode rodar na
    # mesma transacao que referencia o valor novo, daí o bloco autocommit
    # isolado aqui (nenhuma linha desta migration usa o valor).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE tipo_execucao ADD VALUE IF NOT EXISTS 'TENDENCIA_VEGETACAO'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tendencia_vegetacao_area')
    sa.Enum(name="classificacao_tendencia").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

    # Reverte o novo valor de tipo_execucao recriando o tipo sem ele —
    # Postgres nao suporta DROP VALUE em enum. Seguro aqui porque, em
    # qualquer ambiente de dev fazendo downgrade logo apos o upgrade,
    # execucao_processamento nao tera linhas usando 'TENDENCIA_VEGETACAO'.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE tipo_execucao RENAME TO tipo_execucao_old")
        op.execute(
            "CREATE TYPE tipo_execucao AS ENUM "
            "('INGESTAO_CLIMA', 'INGESTAO_SATELITE', 'INDICE_VEGETACAO', 'DIAGNOSTICO', "
            "'CENARIO', 'AVALIACAO_REPRESENTATIVIDADE')"
        )
        op.execute(
            "ALTER TABLE execucao_processamento "
            "ALTER COLUMN tipo TYPE tipo_execucao USING tipo::text::tipo_execucao"
        )
        op.execute("DROP TYPE tipo_execucao_old")
