"""fase 3 vegetacao item stac ativos qualidade

Revision ID: f6de4a12b01d
Revises: 65994b4484fe
Create Date: 2026-09-13 19:37:07.533551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6de4a12b01d'
down_revision: Union[str, None] = '65994b4484fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    qualidade_indice_vegetacao = sa.Enum("SUFICIENTE", "INSUFICIENTE", name="qualidade_indice_vegetacao")
    qualidade_indice_vegetacao.create(op.get_bind(), checkfirst=True)

    op.add_column('cena_satelite', sa.Column('item_stac_id', sa.String(length=120), nullable=False, server_default=''))
    op.alter_column('cena_satelite', 'item_stac_id', server_default=None)
    op.add_column('cena_satelite', sa.Column('ativos', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.create_unique_constraint('uq_cena_satelite_item_stac_id', 'cena_satelite', ['item_stac_id'])
    op.add_column('indice_vegetacao_area', sa.Column('qualidade', qualidade_indice_vegetacao, nullable=False))
    op.create_unique_constraint('uq_indice_vegetacao_area_cena_tipo', 'indice_vegetacao_area', ['area_produtiva_id', 'cena_id', 'tipo'])

    # Novo valor no enum status_processamento_cena (Fase 3 marca cenas
    # sobrepostas por outra do mesmo dia como redundantes, sem apagar sua
    # evidencia). ALTER TYPE ... ADD VALUE nao pode rodar na mesma transacao
    # que referencia o valor novo, daí o bloco autocommit isolado aqui.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE status_processamento_cena ADD VALUE IF NOT EXISTS 'REDUNDANTE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_indice_vegetacao_area_cena_tipo', 'indice_vegetacao_area', type_='unique')
    op.drop_column('indice_vegetacao_area', 'qualidade')
    sa.Enum(name="qualidade_indice_vegetacao").drop(op.get_bind(), checkfirst=True)
    op.drop_constraint('uq_cena_satelite_item_stac_id', 'cena_satelite', type_='unique')
    op.drop_column('cena_satelite', 'ativos')
    op.drop_column('cena_satelite', 'item_stac_id')
    # ### end Alembic commands ###

    # Reverte o novo valor de status_processamento_cena recriando o tipo sem
    # ele — Postgres nao suporta DROP VALUE em enum. Seguro aqui porque, em
    # qualquer ambiente de dev fazendo downgrade logo apos o upgrade,
    # cena_satelite nao tera linhas usando 'REDUNDANTE'.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE status_processamento_cena RENAME TO status_processamento_cena_old")
        op.execute(
            "CREATE TYPE status_processamento_cena AS ENUM "
            "('PENDENTE', 'PROCESSADA', 'REJEITADA')"
        )
        op.execute(
            "ALTER TABLE cena_satelite "
            "ALTER COLUMN status_processamento TYPE status_processamento_cena "
            "USING status_processamento::text::status_processamento_cena"
        )
        op.execute("DROP TYPE status_processamento_cena_old")
